# Use the same Python version you developed with
runtime: python311 

# The entrypoint tells App Engine how to start your app using gunicorn
entrypoint: gunicorn -b :$PORT 'app:app'

# This section handles automatic scaling based on traffic
automatic_scaling:
  min_instances: 0
  max_instances: 1 
  # Start with 1 max instance to stay within the free tier

# For this version of App Engine, environment variables are set directly here.
# WARNING: DO NOT COMMIT THIS FILE WITH REAL SECRETS TO A PUBLIC REPOSITORY.
env_variables:
  # Flask App Secret Key
  SECRET_KEY: 'PASTE_A_NEW_RANDOM_SECRET_KEY_HERE'

  # Your Google OAuth Credentials
  GOOGLE_CLIENT_ID: 'PASTE_YOUR_GOOGLE_CLIENT_ID_HERE'
  GOOGLE_CLIENT_SECRET: 'PASTE_YOUR_GOOGLE_CLIENT_SECRET_HERE'

  # --- Cloud SQL Database Connection String ---
  # Replace with your actual database connection string
  SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://USER:PASS@/DB_NAME?host=/cloudsql/PROJECT:REGION:INSTANCE'
